# Generated by Django 2.2.5 on 2021-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('parent', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('portfolios', models.TextField(blank=True)),
            ],
        ),
    ]
