# Generated by Django 2.2.5 on 2021-09-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
